from core.database import init_db, save_signal
from core.alerts import should_send_alert
from core.health import log_run
from core.config import PORTFOLIO

from agents.technical_agent import get_technical_indicators
from agents.sentiment_agent import analyze_sentiment
from agents.bull_agent import bull_case
from agents.bear_agent import bear_case
from agents.debate_agent import debate_decision
from agents.risk_agent import assess_risk

from agents.discovery_agent import discover_opportunities
from agents.ranking_agent import rank_stocks
from agents.rebalance_agent import rebalance_advice

from agents.quant_agent import compute_quant_score
from agents.performance_agent import update_performance
from agents.metrics_agent import get_accuracy

from utils.emailer import send_email

import datetime


def process_stock(ticker):
    """
    Runs full AI pipeline for a single stock
    """

    indicators = get_technical_indicators(ticker)

    sentiment = analyze_sentiment(ticker)

    bull = bull_case(ticker, indicators, sentiment)

    bear = bear_case(ticker, indicators, sentiment)

    signal = debate_decision(bull, bear)

    confidence = abs(
        bull.get("bull_score", 50) - bear.get("bear_score", 50)
    ) / 100

    risk_level = assess_risk(indicators)

    quant_score = compute_quant_score(
        indicators,
        sentiment,
        risk_level
    )

    alert_needed = should_send_alert(ticker, signal)

    save_signal(
        ticker,
        signal,
        confidence,
        indicators["price"]
    )

    report = f"""
--------------------------------------------------

Stock: {ticker}

Price: {round(indicators['price'],2)}

Technical Indicators
SMA20: {round(indicators['SMA_20'],2)}
SMA50: {round(indicators['SMA_50'],2)}

Sentiment Analysis
Summary: {sentiment.get("summary","No news summary available")}

Bullish Argument
{bull.get("argument","N/A")}

Bearish Argument
{bear.get("argument","N/A")}

Risk Level: {risk_level}

Quant Score: {quant_score}/100

FINAL DECISION: {signal}

Confidence Score: {round(confidence,2)}

--------------------------------------------------
"""

    return report, signal


def main():

    init_db()

    report_sections = []

    portfolio_results = []

    # ----- Portfolio Monitoring -----

    for ticker in PORTFOLIO:

        try:

            report, signal = process_stock(ticker)

            report_sections.append(report)

            portfolio_results.append({
                "ticker": ticker,
                "signal": signal
            })

        except Exception as e:

            report_sections.append(
                f"\nError processing {ticker}: {str(e)}\n"
            )

    # ----- Market Opportunity Discovery -----

    opportunities = discover_opportunities()

    ranked = rank_stocks(opportunities)

    # ----- Portfolio Rebalancing Advice -----

    rebalance = rebalance_advice(portfolio_results)

    # ----- Build Email Report -----

    full_report = f"""
AUTONOMOUS INVESTMENT AI REPORT
Generated by Multi-Agent Financial Intelligence System
Date: {datetime.datetime.utcnow().strftime("%Y-%m-%d")}

===== DAILY INVESTMENT AI REPORT =====
"""

    full_report += "\n".join(report_sections)

    # ----- Top Market Opportunities -----

    full_report += "\n\n===== TOP MARKET OPPORTUNITIES =====\n"

    if ranked:

        for stock in ranked:

            full_report += f"""
Stock: {stock['ticker']}
Trend Score: {stock['score']}
Current Price: {round(stock['price'],2)}
Recommendation: Strong upward momentum detected
"""

    else:

        full_report += "No strong opportunities detected today.\n"

    # ----- Portfolio Advice -----

    full_report += "\n\n===== PORTFOLIO REBALANCE ADVICE =====\n"

    for advice in rebalance:
        full_report += f"{advice}\n"

    # ----- Weekly Strategy Note -----

    today = datetime.datetime.utcnow().weekday()

    if today == 0:

        full_report += """

===== WEEKLY STRATEGY NOTE =====

The AI agent suggests monitoring macroeconomic indicators,
technology sector momentum, and maintaining diversification
to manage risk.

"""

    # ----- AI Performance Tracking -----

    update_performance()

    accuracy = get_accuracy()

    full_report += f"""

===== AI PERFORMANCE METRICS =====

Prediction Accuracy: {accuracy} %

This metric evaluates how often the AI's BUY/SELL signals
correctly predicted future price movements.

"""

    # ----- Send Email -----

    send_email(full_report)

    # ----- Log Run -----

    log_run(
        "SUCCESS",
        "Daily AI investment agent run completed"
    )


if __name__ == "__main__":
    main()