from core.database import init_db, save_signal
from core.alerts import should_send_alert
from core.health import log_run
from core.config import PORTFOLIO

from agents.technical_agent import get_technical_indicators
from agents.sentiment_agent import analyze_sentiment
from agents.bull_agent import bull_case
from agents.bear_agent import bear_case
from agents.debate_agent import debate_decision
from agents.risk_agent import assess_risk

from agents.discovery_agent import discover_opportunities
from agents.ranking_agent import rank_stocks
from agents.rebalance_agent import rebalance_advice

from agents.quant_agent import compute_quant_score


from utils.emailer import send_email

import datetime


def process_stock(ticker):
    """
    Runs full AI pipeline for a single stock
    """

    indicators = get_technical_indicators(ticker)

    sentiment = analyze_sentiment(ticker)

    bull = bull_case(ticker, indicators, sentiment)

    bear = bear_case(ticker, indicators, sentiment)

    signal = debate_decision(bull, bear)

    bull_score = bull.get("bull_score", 50)
    bear_score = bear.get("bear_score", 50)

    score_diff = abs(bull_score - bear_score)

    # normalize confidence
    confidence = round(
        max(0.2, min(score_diff / 50, 0.95)),
        2
    )

    risk_level = assess_risk(indicators)

    quant_score = compute_quant_score(
        indicators,
        sentiment,
        risk_level
    )

    alert_needed = should_send_alert(ticker, signal)

    save_signal(
        ticker,
        signal,
        confidence,
        indicators["price"]
    )

    report = f"""
--------------------------------------------------

Stock: {ticker}

Price: {round(indicators['price'],2)}

Technical Indicators
SMA20: {round(indicators['SMA_20'],2)}
SMA50: {round(indicators['SMA_50'],2)}

Sentiment Analysis
Summary: {sentiment.get("summary","No news summary available")}

Bullish Argument
{bull.get("argument","N/A")}

Bearish Argument
{bear.get("argument","N/A")}

Risk Level: {risk_level}

Quant Score: {quant_score}/100

FINAL DECISION: {signal}

Confidence Score: {round(confidence,2)}

--------------------------------------------------
"""

    return report, signal


def main():

    init_db()

    report_sections = []

    portfolio_results = []

    # ----- Portfolio Monitoring -----

    for ticker in PORTFOLIO:

        try:

            report, signal = process_stock(ticker)

            report_sections.append(report)

            portfolio_results.append({
                "ticker": ticker,
                "signal": signal
            })

        except Exception as e:

            report_sections.append(
                f"\nError processing {ticker}: {str(e)}\n"
            )

    # ----- Market Opportunity Discovery -----

    opportunities = discover_opportunities()

    ranked = rank_stocks(opportunities)

    candidate_tickers = [o["ticker"] for o in opportunities]

    # ----- Portfolio Rebalancing Advice -----

    rebalance = rebalance_advice(portfolio_results)

    # ----- Build Email Report -----

    full_report = f"""
AUTONOMOUS INVESTMENT AI REPORT
Generated by Multi-Agent Financial Intelligence System
Date: {datetime.datetime.utcnow().strftime("%Y-%m-%d")}

    
===== DAILY INVESTMENT AI REPORT =====
"""

    full_report += "\n".join(report_sections)

    # ----- Top Market Opportunities -----

    # ----- Top Market Opportunities -----

    full_report += "\n\n===== TOP MARKET OPPORTUNITIES =====\n"

    if ranked:

        for stock in ranked:

            try:

                indicators = get_technical_indicators(stock["ticker"])

                price = indicators["price"]
                sma20 = indicators["SMA_20"]
                sma50 = indicators["SMA_50"]

                momentum_proof = []

                if price > sma20:
                    momentum_proof.append("Price > SMA20")

                if price > sma50:
                    momentum_proof.append("Price > SMA50")

                proof_text = ", ".join(momentum_proof)

                full_report += f"""
    Stock: {stock['ticker']}

    Current Price: {round(price,2)}

    Technical Proof
    SMA20: {round(sma20,2)}
    SMA50: {round(sma50,2)}

    Momentum Evidence:
    {proof_text}

    Scanner Score: {stock['score']}

    Reason:
    Stock passed the market scanner because it shows positive momentum relative to moving averages.
    """

            except:
                continue

    else:

        full_report += "No strong opportunities detected today.\n"

    # ----- Portfolio Advice -----

    full_report += "\n\n===== PORTFOLIO REBALANCE ADVICE =====\n"

    for advice in rebalance:
        full_report += f"{advice}\n"

    # ----- Weekly Strategy Note -----

    today = datetime.datetime.utcnow().weekday()

    if today == 0:

        full_report += """

===== WEEKLY STRATEGY NOTE =====

The AI agent suggests monitoring macroeconomic indicators,
technology sector momentum, and maintaining diversification
to manage risk.

"""

    # ----- Send Email -----

    send_email(full_report)

    # ----- Log Run -----

    log_run(
        "SUCCESS",
        "Daily AI investment agent run completed"
    )


if __name__ == "__main__":
    main()